# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TraineeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TraineeProject

	pod 'FBSDKLoginKit'
  	pod 'Firebase/Core'
  	pod 'Firebase/Auth'
  	pod 'GoogleSignIn'


  target 'TraineeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TraineeProjectUITests' do
    # Pods for testing
  end

end
